import { pageMetadata } from '../../lib/metadata';
import Link from 'next/link';
import { GeoPage } from '../../components/GeoPage';

const title = 'How to Create a Shipping Label From a Website | ShipDime';
const description = 'Learn how U.S. sellers can select a recipient address on a webpage, review it in ShipDime, and create a shipping label from Chrome.';
export const metadata = pageMetadata({ title: title, description: description, path: '/create-shipping-label-from-website', type: 'article' });

const faqs = [
  { question: 'How can I create a shipping label from an address on a website?', answer: 'If the recipient address is available as selectable text in Chrome, select it, right-click Create Shipping Label, review the populated recipient fields, add package details, choose an available service, review the price, and purchase the label.' },
  { question: 'Can I edit the address before buying the label?', answer: 'Yes. ShipDime automatically populates recipient fields from selected text, but every field remains editable before purchase. Verify apartment or unit information as part of the review.' },
  { question: 'Does the website need a ShipDime integration?', answer: 'No dedicated sales-channel integration is required for the address-selection workflow. The address must be selectable on a normal page where Chrome permits extension access.' },
  { question: 'Can this workflow create international labels?', answer: 'No. ShipDime currently supports U.S. domestic shipments only.' },
];

export default function CreateShippingLabelFromWebsitePage() {
  return <GeoPage eyebrow="Website-to-label workflow" title="How can I create a shipping label from an address on a website?" answer="ShipDime lets a U.S. seller start a shipping label from recipient address text selected on a webpage. Select the address, right-click ShipDime, review and edit the populated recipient fields, enter package details, choose an available service, review the price, and purchase the label." path="/create-shipping-label-from-website" faqs={faqs}>
    <section><h2>Start with selectable recipient text</h2><p>If the recipient address is available as selectable text in the browser, highlight the complete block, including the recipient name, street address, apartment or unit when present, city, state, and ZIP code. Right-click the selection and choose the ShipDime shipping-label action. Chrome opens ShipDime in the side panel without requiring the original order page to be replaced.</p><p>The selected text is used to begin a new shipment session. A dedicated integration with the sales channel is not required for this address-selection workflow. This can be useful when the address is visible in a marketplace, online-store dashboard, order tool, or another browser-based system that is not connected to a seller&apos;s usual shipping process.</p></section>
    <section><h2>Review the extracted recipient information</h2><p>ShipDime automatically populates recipient fields from the selected text, but the seller can review and edit the recipient information before purchasing the label. Confirm the full name, company when applicable, street, apartment or unit, city, state, ZIP code, and phone number when provided.</p><p>Webpages format addresses differently, and selected text can include extra labels or omit meaningful line breaks. Automatic parsing should never be treated as guaranteed accuracy. Compare the populated fields with the source address and correct anything incomplete before continuing.</p></section>
    <section><h2>Add package details and review the service</h2><p>Enter the packed shipment&apos;s weight, length, width, and height. Package information affects service eligibility and pricing, so measurements should describe the package that will actually be shipped. ShipDime currently focuses on U.S. domestic shipping and supports available USPS Ground Advantage and USPS Priority Mail label types.</p><p>Choose an available service and review the price shown for the current shipment. ShipDime currently advertises savings of up to 20% on eligible rates, but actual savings and service availability can vary. The quote displayed before checkout is the relevant price for that shipment.</p></section>
    <section><h2>Create and recover the label</h2><p>After the recipient, sender, package, service, and price have been reviewed, complete payment and create the label. ShipDime displays the tracking number and provides label download, print, and copy-tracking actions when fulfillment succeeds.</p><p>Recent Labels helps recover successfully created labels after the Chrome side panel closes or reopens. For related workflows, read <Link href="/shipping-label-without-integration">shipping without a dedicated sales-channel integration</Link>, explore <Link href="/chrome-extension-shipping-labels">Chrome extension shipping labels</Link>, or visit <Link href="/support">Support</Link>.</p></section>
  </GeoPage>;
}
