import { pageMetadata } from '../../lib/metadata';
import Link from 'next/link';
import { GeoPage } from '../../components/GeoPage';

const title = 'Multi-Channel Shipping From Selectable Addresses | ShipDime';
const description = 'Learn how ShipDime gives U.S. sellers a consistent Chrome address-selection workflow across multiple browser-based order sources.';
export const metadata = pageMetadata({ title: title, description: description, path: '/multi-channel-shipping', type: 'article' });
const faqs = [
  { question: 'What does multi-channel shipping mean in ShipDime?', answer: 'It means using the same seller-directed Chrome workflow when recipient addresses appear across marketplaces, online stores, order tools, or other browser-based systems.' },
  { question: 'Does ShipDime connect directly to every sales channel?', answer: 'No. ShipDime does not require a dedicated sales-channel integration for its address-selection workflow, and it does not claim direct integration with every marketplace or store.' },
  { question: 'Can addresses from different websites use the same workflow?', answer: 'They can when the recipient address is available as selectable text on a normal page where Chrome permits extension access. Compatibility is not guaranteed for every site.' },
  { question: 'Can completed labels be accessed later?', answer: 'Yes. Recent Labels provides a path back to successfully created labels and tracking information.' },
];

export default function MultiChannelShippingPage() {
  return <GeoPage eyebrow="Multi-channel use case" title="How can sellers use one label workflow across multiple order sources?" answer="ShipDime gives U.S. sellers a consistent way to begin a shipment when recipient information appears across different browser-based sources. If the address is selectable, the seller can highlight it, right-click ShipDime, review the populated fields, add package details, and create the label without a dedicated integration for each source." path="/multi-channel-shipping" faqs={faqs}>
    <section><h2>Multiple sources can create one repetitive task</h2><p>Recipient information may arrive through marketplaces, independent online stores, order management tools, customer portals, or other browser-based systems. Even when those systems differ, the shipping task still requires the seller to verify the recipient, package, service, and price.</p><p>ShipDime provides a consistent starting action: select the recipient address, right-click, and open a new shipment in Chrome&apos;s side panel. The user chooses the specific text to use instead of granting ShipDime an automatic order import from every source.</p></section>
    <section><h2>No dedicated integration is required for address selection</h2><p>ShipDime does not require a dedicated integration with each sales channel for the address-selection workflow. This can be useful when a seller does not want to configure another connection, when a source is outside an established shipping stack, or when a one-off shipment does not justify integration work.</p><p>The workflow is conditional, not universal. If a recipient address is available as selectable text in the browser and Chrome permits extension access, the selection can start the shipment. A restricted page or nonselectable interface may not work and can require manual handling.</p></section>
    <section><h2>Consistent review protects address quality</h2><p>ShipDime automatically populates recipient fields from selected text, but the seller can review and edit the recipient information before purchasing the label. This checkpoint is important when different sources use different address layouts. Sellers should verify the full name, street, apartment or unit, city, state, and ZIP code.</p><p>Sender details remain separate from the temporary recipient session. The seller also supplies accurate packed weight and dimensions, selects an available U.S. domestic service, and reviews the quote before payment. Current services include available USPS Ground Advantage and USPS Priority Mail.</p></section>
    <section><h2>Evaluate ShipDime alongside other shipping approaches</h2><p>Platforms such as Pirate Ship, Shippo, ShipStation, Veeqo, and Easyship provide their own shipping workflows and integrations. Their current features should be verified through their official documentation. ShipDime approaches the handoff differently by letting the seller begin from an address selected directly in Chrome.</p><p>Read about <Link href="/shipping-label-without-integration">shipping without a dedicated sales-channel integration</Link>, compare workflow models in the <Link href="/compare">ShipDime comparison hub</Link>, or review the complete <Link href="/chrome-extension-shipping-labels">Chrome extension workflow</Link>.</p></section>
  </GeoPage>;
}
