export const metadata = { title: 'Privacy Policy — ShipDime', description: 'How ShipDime handles information used to create shipping labels.' };

export default function PrivacyPage() {
  return <div className="shell legal-page"><p className="eyebrow">Privacy</p><h1>ShipDime Privacy Policy</h1><p className="updated">Last updated August 11, 2026</p><p className="lead">This policy explains the information ShipDime processes when you use the website, Chrome extension, checkout, and shipping-label service.</p>
    <section><h2>Information processed by ShipDime</h2><p>To prepare and create a label, ShipDime processes highlighted text; recipient and sender names, companies, phone numbers, and shipping addresses; package weight and dimensions; selected label type; shipping quotes; order status and amount; tracking numbers; and label/reference information.</p></section>
    <section><h2>Information stored locally in Chrome</h2><p>The extension uses Chrome local storage for your saved sender address, the current highlighted text and parsed recipient, selection and extraction status, active order identifiers and status, the current completed shipment, and up to 10 recent labels and order references. Recent-label records include a limited shipment summary, tracking information, dimensions, service, and price. You can clear extension data using Chrome or the extension’s development reset control when available.</p></section>
    <section><h2>Information sent to ShipDime</h2><p>When requesting a quote, starting checkout, creating a label, checking order status, recovering a label, or downloading a label, the extension sends the information needed for that operation to the ShipDime backend. Address extraction itself currently occurs in the browser, but shipment details are sent to the backend when requesting shipping services.</p></section>
    <section><h2>Backend and database records</h2><p>ShipDime stores shipping quotes and shipment snapshots, including recipient and sender details, package details, selected service, pricing, quote expiration, and selection reference. It also stores orders, payment and fulfillment status, amount and currency, checkout/payment transaction identifiers, errors needed for support, label records, tracking numbers, and label references. These records support payment verification, duplicate prevention, label recovery, downloads, and customer support.</p></section>
    <section><h2>Payments</h2><p>Payment-card details are entered in a secure hosted checkout operated by our payment processor. The extension and ShipDime backend do not store your full card number or security code. ShipDime stores transaction identifiers and payment status needed to associate payment with an order and prevent duplicate fulfillment.</p></section>
    <section><h2>Service providers and disclosures</h2><p>ShipDime shares information with service providers only as needed to calculate shipping options, process payment, create and retrieve labels, host the service, store operational records, and provide support. We may also disclose information when required by law, to prevent fraud or misuse, or to protect users and the service.</p></section>
    <section><h2>Retention and deletion</h2><p>ShipDime’s current application does not define a fixed retention or automatic deletion period for backend quote, order, and label records. Local extension data remains until it is replaced, cleared by the extension, or removed through Chrome. Contact us to ask about access or deletion; requests may be limited where records must be retained for security, legal, accounting, fraud-prevention, or shipping-support purposes.</p></section>
    <section><h2>Security and choices</h2><p>We use technical and organizational safeguards appropriate to the service. No system can guarantee absolute security. Review highlighted text before starting a shipment, keep your browser profile secure, and avoid selecting unrelated sensitive information.</p></section>
    <section><h2>Contact</h2><p>Questions or privacy requests: <a href="mailto:info@veycell.org">info@veycell.org</a>.</p></section>
  </div>;
}
