import { pageMetadata } from '../../lib/metadata';
export const metadata = pageMetadata({ title: 'Terms — ShipDime', description: 'Terms for using ShipDime shipping-label services.', path: '/terms', type: 'website' });

export default function TermsPage() {
  return <div className="shell legal-page"><p className="eyebrow">Terms</p><h1>ShipDime Terms of Service</h1><p className="updated">Last updated August 11, 2026</p><p className="lead">These terms govern your use of the ShipDime website, Chrome extension, and shipping-label service.</p>
    <section><h2>Using ShipDime</h2><p>ShipDime helps you prepare, purchase, access, and manage shipping labels. You must be legally able to enter into these terms and use the service only for lawful shipments.</p></section>
    <section><h2>Your shipment information</h2><p>You are responsible for reviewing and providing complete, accurate recipient and sender information, package weight and dimensions, package contents, and service selection. You must ensure the package is properly packed and eligible for the selected carrier service.</p></section>
    <section><h2>Prices and payment</h2><p>ShipDime shows the applicable price before purchase. Savings may vary by shipment and service. Payment must complete successfully before label fulfillment begins. Do not initiate another payment for an order already marked paid or processing; use label recovery or contact support instead.</p></section>
    <section><h2>Labels, cancellation, and refunds</h2><p>You review shipment information before purchase. The current product treats a successfully generated shipping label as final and nonrefundable. A canceled checkout does not complete payment or create a label. If payment succeeds but label creation fails, do not pay again; use the recovery action or contact support.</p><p>Business policies for unused-label voids, refunds required by law, duplicate-payment resolution, and carrier adjustments are not yet fully defined and may require case-by-case review.</p></section>
    <section><h2>Carrier services and tracking</h2><p>Service availability, transit times, acceptance, delivery, tracking events, and carrier adjustments depend on the selected shipping service and shipment details. Displayed estimates are not guarantees unless explicitly identified as guaranteed.</p></section>
    <section><h2>Prohibited shipments</h2><p>You may not use ShipDime to ship illegal, hazardous, restricted, sanctioned, fraudulent, or prohibited items, or to violate postal, carrier, customs, export, or import rules. You are responsible for knowing and following rules applicable to your shipment.</p></section>
    <section><h2>Access and service changes</h2><p>We may limit or suspend access to protect ShipDime, users, carriers, or payment systems; comply with law; address misuse; or maintain the service. Features and supported services may change.</p></section>
    <section><h2>Support</h2><p>For label access, tracking, payment, or fulfillment problems, contact <a href="mailto:info@veycell.org">info@veycell.org</a> and include your ShipDime reference number when available. Never email payment-card information.</p></section>
    <section><h2>Contact</h2><p>Questions about these terms: <a href="mailto:info@veycell.org">info@veycell.org</a>.</p></section>
  </div>;
}
