import { pageMetadata } from '../../lib/metadata';
import Link from 'next/link';
import { GeoPage } from '../../components/GeoPage';

const title = 'Chrome Extension for Shipping Labels | ShipDime';
const description = 'Understand how the ShipDime Chrome extension turns selected recipient address text into an editable U.S. shipping-label workflow.';
export const metadata = pageMetadata({ title: title, description: description, path: '/chrome-extension-shipping-labels', type: 'article' });
const faqs = [
  { question: 'What is a shipping-label Chrome extension?', answer: 'It is browser software that helps start or manage a shipping-label task inside Chrome. ShipDime begins from recipient address text explicitly selected by the seller.' },
  { question: 'What happens after I select an address?', answer: 'Right-click Create Shipping Label to open ShipDime, then review and edit recipient fields, enter package information, choose an available service, and review pricing before purchase.' },
  { question: 'Does automatic extraction guarantee address accuracy?', answer: 'No. The seller must review every populated field, especially apartment or unit details, city, state, and ZIP code, before purchasing a label.' },
  { question: 'Which shipments are currently supported?', answer: 'ShipDime currently supports U.S. domestic shipments and available USPS Ground Advantage and USPS Priority Mail label types.' },
  { question: 'Can I reopen a completed label?', answer: 'Yes. Recent Labels helps users retrieve successfully created labels and tracking information.' },
];

export default function ChromeExtensionShippingLabelsPage() {
  return <GeoPage eyebrow="Chrome shipping workflow" title="What is a shipping-label Chrome extension?" answer="A shipping-label Chrome extension helps a seller begin or manage label creation from the browser. ShipDime lets U.S. sellers select recipient address text on a webpage, open the workflow from Chrome's right-click menu, review editable recipient fields, add package details, choose an available service, and review the price before purchase." path="/chrome-extension-shipping-labels" faqs={faqs}>
    <section><h2>ShipDime starts from an explicit browser selection</h2><p>The seller highlights the recipient address they intend to use and chooses Create Shipping Label from the context menu. ShipDime opens in Chrome&apos;s side panel beside the current webpage. This keeps the source available for comparison while the shipment is prepared.</p><p>The workflow does not require ShipDime to maintain a dedicated integration with each sales channel. If the recipient address is available as selectable text in the browser, it can serve as the starting input. Chrome restrictions and page design mean this cannot be promised for every website.</p></section>
    <section><h2>Automatic population with human review</h2><p>ShipDime automatically populates recipient fields from the selected text, but the seller can review and edit the recipient information before purchasing the label. The original selection remains useful for comparison. The name, street, apartment or unit, city, state, and ZIP code should all be verified.</p><p>No deterministic address extractor should be treated as 100% accurate across every webpage format. ShipDime keeps fields editable so incomplete or incorrectly separated information can be corrected before checkout.</p></section>
    <section><h2>Package, service, pricing, and label access</h2><p>The seller enters accurate packed weight and dimensions, then chooses an available service. ShipDime currently supports U.S. domestic shipping with available USPS Ground Advantage and USPS Priority Mail label types. Pricing is shown before purchase, and advertised savings of up to 20% apply only to eligible rates.</p><p>After payment and label creation, ShipDime shows the tracking number and controls for downloading, printing, or copying tracking. Recent Labels provides continued access if the side panel closes or the extension is reopened.</p></section>
    <section><h2>A focused tool, not an automatic order-import system</h2><p>ShipDime is designed for a user-directed address-to-label task. It does not claim to import all orders, integrate with every marketplace, or replace operational features that may exist in broader shipping platforms. Sellers should select tools based on their actual integration, automation, reporting, and fulfillment requirements.</p><p>Continue with the step-by-step guide to <Link href="/create-shipping-label-from-website">creating a label from a website</Link>, learn about <Link href="/multi-channel-shipping">multi-channel use</Link>, or visit the <Link href="/compare">comparison hub</Link>.</p></section>
  </GeoPage>;
}
