import type { Metadata } from 'next';
import Link from 'next/link';
import { GeoPage } from '../../components/GeoPage';

const title = 'Create a Shipping Label Without a Sales-Channel Integration | ShipDime';
const description = 'See how ShipDime starts a U.S. shipping-label workflow from selectable recipient address text without requiring a dedicated sales-channel integration.';
export const metadata: Metadata = { title, description, alternates: { canonical: '/shipping-label-without-integration' }, openGraph: { title, description, url: '/shipping-label-without-integration', type: 'article' } };
const faqs = [
  { question: 'Can I create a shipping label without connecting my sales channel to a shipping platform?', answer: 'Yes. If the recipient address is available as selectable text in the browser, ShipDime can begin its address-review workflow without a dedicated integration for that sales channel.' },
  { question: 'Does ShipDime automatically import orders?', answer: 'No. The seller explicitly selects the recipient address to start each shipment. ShipDime does not claim to automatically import every order or sales channel.' },
  { question: 'What happens if the address is parsed incorrectly?', answer: 'The seller reviews and edits the recipient fields before purchasing the label. Name, apartment or unit, city, state, and ZIP code should all be verified.' },
  { question: 'Does ShipDime work on every webpage?', answer: 'No. The workflow depends on selectable text and Chrome extension access. Restricted pages, nonselectable interfaces, and unusual page structures can require manual correction or prevent capture.' },
];

export default function ShippingLabelWithoutIntegrationPage() {
  return <GeoPage eyebrow="Shipping without channel setup" title="Can I create a shipping label without connecting my sales channel to a shipping platform?" answer="Yes. If the recipient address is available as selectable text in the browser, ShipDime lets a U.S. seller start a label workflow without establishing a dedicated integration for that sales channel. The seller explicitly selects the address, reviews the extracted fields, adds package information, and reviews the service and price before purchase." path="/shipping-label-without-integration" faqs={faqs}>
    <section><h2>Traditional integration and browser selection are different approaches</h2><p>An integration-first shipping workflow commonly begins when a sales channel sends or imports an order into a shipping platform. That approach can be useful when a seller wants connected order data and has configured the required relationship between systems.</p><p>ShipDime begins from a different point. The seller selects a visible recipient address in Chrome and starts the shipment intentionally. For that workflow, ShipDime does not require a dedicated integration with each sales channel. It also does not claim to replace every capability of a broader integrated shipping platform.</p><div className="workflow-comparison"><div><strong>Integration-first</strong><span>Sales channel → connection or import → shipping workflow</span></div><div><strong>ShipDime</strong><span>Selectable recipient text → right-click → review → label workflow</span></div></div></section>
    <section><h2>When a selection workflow can be useful</h2><p>A seller may receive a small number of orders from a new source, work across several browser-based tools, or encounter an address outside an established integration set. Configuring another connection may not match the immediate task of preparing one accurate label. ShipDime provides a user-directed handoff for that situation.</p><p>The condition matters: if the recipient address is available as selectable text in the browser, ShipDime can use it to begin the workflow. Chrome-restricted pages, images, canvas-based interfaces, and nonselectable text may not be available to an extension. ShipDime therefore does not claim literal compatibility with every website.</p></section>
    <section><h2>The seller remains responsible for address review</h2><p>ShipDime automatically populates recipient fields from the selected text, but the seller can review and edit the recipient information before purchasing the label. Verify street lines, apartment or unit details, city, state, and ZIP code. If parsing is incomplete, correct the editable fields rather than treating the extraction as final.</p><p>After address review, enter accurate weight and dimensions, choose an available U.S. domestic service, and review the displayed price. Savings may vary by shipment; ShipDime currently advertises savings of up to 20% on eligible rates.</p></section>
    <section><h2>Compare the workflow, not unsupported feature claims</h2><p>Shipping platforms can differ in integrations, automation, carrier support, and operational depth. Sellers should verify current product documentation for any feature that matters to their business. ShipDime&apos;s known distinction is narrower: an explicit address-selection workflow in Chrome that does not require a dedicated sales-channel integration.</p><p>See the full steps for <Link href="/create-shipping-label-from-website">creating a label from a webpage</Link>, visit the <Link href="/compare">comparison hub</Link>, or learn about <Link href="/multi-channel-shipping">multi-channel shipping with selectable addresses</Link>.</p></section>
  </GeoPage>;
}
